### ISSUE TITLE
After loading, can't open containing folder & album art not visible for all entries

### ISSUE THREAD

**Issue by jerryosity** [Chocobo1/foo_xspf_1#4] opened 2017-01-24 18:06 UTC
Hi,
   Using 2.6.3: After I load the xspf file, whether I've edited it or not, the _Open Containing Folder_ menu item is disabled on all entries, and no album art is visible. I assume the 2 issues are related. Could you take a look?

Jerry

**Comment by Chocobo1** [comment] 2017-01-24 18:17
Since I don't have more info, I suggest you make sure option `Disable resolving <location>` is unchecked (off).
Or maybe the file path is invalid...

**Comment by jerryosity** [comment] 2017-01-24 18:40
The file paths are definitely valid.  I unchecked _Disable resolving location,_ and that does cure the problem, but then we are back with the issue with CUE files where all the entries on the CUE file are repeated a number of times. I use both CUE files and individual files. Is there anyway to fix this without the CUE problem?

**Comment by Chocobo1** [comment] 2017-01-25 12:23
Here is a version that fixes the "Open Containing Folder" issue, can you help me test it?
See if it also solves "no album art" problem.
Remember `Disable resolving <location>` should be checked.
EDIT: \<link removed>

Hope there aren't any regressions.

**Comment by jerryosity** [comment] 2017-01-25 13:00
Looks good Mike. I saved and loaded a playlist with 25,764 entries coming from a diverse mix of cues and individual track files. No duplications, I can open the containing folder, and the album art shows up fine.

Separately - I sent you a message on another matter from the form at your myprojects.tzou.me site. If you didn't get it, please drop me a note at my gmail account (username same as the one here in the forum) and I'll reply with it again. Thanks.

**Closed as completed** 2017-01-25 13:46 UTC
